### ISSUE TITLE
question [do this work?]

### ISSUE THREAD

**Issue by mrc4tt** [hroost/ovh_ip-mitigation_exporter#1]
Hi,

Do this still work? :-)

Do you have any idea about I can create a "dashboard" of it in Grafana?

README doesn't say much information, on how I can get the metrics to work. :-)
Do I need to run the .py script into the server?

**Comment by hroost** [comment]
Hi @mrc4tt , it works.
I will update this repo a bit latter with example of Grafana dashboard template.

To get the metrics just run container like described in readme and use Prometheus to scrape metrics endpoint

**Comment by hroost** [comment]
[Here](https://github.com/hroost/ovh_ip-mitigation_exporter/blob/master/grafana-dashboard.json) you can find a simple example of dashboard

**Comment by mrc4tt** [comment]
> [Here](https://github.com/hroost/ovh_ip-mitigation_exporter/blob/master/grafana-dashboard.json) you can find a simple example of dashboard

Thanks you.
How shall I add the server? because I see no data (as screenshot)
![image](https://github.com/hroost/ovh_ip-mitigation_exporter/assets/5301047/c141cf86-3b19-458a-ae44-1204a55d0e31)

**Comment by hroost** [comment]
After you have started container just point your prometheus scraping on it - then data would be available in grafana.
p.s. metrics for mitigation Pps & Bps not yet implemented in current release - expecting later.

**Comment by mrc4tt** [comment]
![image](https://github.com/hroost/ovh_ip-mitigation_exporter/assets/5301047/1539b5fc-ae20-4773-87a0-fdd81a017d62)
For example like this, or would it be incorrect?

**Comment by hroost** [comment]
Yes, and don't forget to update (if needed) the datasource (pick your created) inside grafana charts where queries are located

**Comment by mrc4tt** [comment]
Do you mean these import dashboards stuff?
![image](https://github.com/hroost/ovh_ip-mitigation_exporter/assets/5301047/5d21e298-2f65-425c-949d-6d8700c7a5c2)
